
export const venueMap: Record<number, string> = {
  1: "RC Auditorium",
  2: "Atrium",
  3: "Freedom Hall",
  4: "Nelion dome",
  5: "Satima Auditorium",
  6: "Lenana dome",
  7: "Nyana dome",
  8: "Farm House",
  9: "Challenge Course",
  10: "Chancellors Court"
};

export const EventsData = [
    {
        "EventID": 4,
        "title": "Web3 & Blockchain Dev Conference",
        "description": "Dive into decentralized tech with thought leaders from across Africa.",
        "VenueID": 4,
        "category": "Tech",
        "date": "2025-08-25",
        "time": "2:00 PM",
        "ticketsPrice": "3000.00",
        "totalTickets": 200,
        "soldTickets": 130,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 6,
        "title": "Data Science Bootcamp: Nairobi Edition",
        "description": "A 2-day crash course for beginners on Python, Pandas, and Machine Learning.",
        "VenueID": 6,
        "category": "Data Science",
        "date": "2025-11-01",
        "time": "8:30 AM",
        "ticketsPrice": "4500.00",
        "totalTickets": 150,
        "soldTickets": 100,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 7,
        "title": "Microsoft Azure Hackfest",
        "description": "Build real-world solutions using Azure Functions, Cosmos DB, and more.",
        "VenueID": 7,
        "category": "Web Dev",
        "date": "2025-10-22",
        "time": "9:30 AM",
        "ticketsPrice": "3000.00",
        "totalTickets": 250,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 9,
        "title": "Tech Women Summit Kenya",
        "description": "Highlighting innovation and leadership among women in the tech industry.",
        "VenueID": 9,
        "category": "Tech",
        "date": "2025-12-01",
        "time": "10:00 AM",
        "ticketsPrice": "2200.00",
        "totalTickets": 400,
        "soldTickets": 320,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 11,
        "title": "Google I/O Extended Nairobi",
        "description": "Explore the latest from Google technologies with the Nairobi dev community.",
        "VenueID": 1,
        "category": "Tech",
        "date": "2025-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 22,
        "title": "AI for Africa Summit",
        "description": "Meet top minds working on responsible AI and digital policy for Africa.",
        "VenueID": 5,
        "category": "Data Science",
        "date": "2025-10-05",
        "time": "11:00 AM",
        "ticketsPrice": "5000.00",
        "totalTickets": 500,
        "soldTickets": 350,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-10-05",
        "updatedAt": "2025-10-05"
    },
    {
        "EventID": 23,
        "title": "Google I/O Extended Nairobi",
        "description": "Explore the latest from Google technologies with the Nairobi dev community.",
        "VenueID": 1,
        "category": "Tech",
        "date": "2025-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 24,
        "title": "Christmass carols",
        "description": "An amazing night of performances",
        "VenueID": 1,
        "category": "Tech",
        "date": "2025-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 25,
        "title": "Christmass carols",
        "description": "An amazing night of performances",
        "VenueID": 1,
        "category": "Tech",
        "date": "2025-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 26,
        "title": "Christmass carols",
        "description": "An amazing night of performances",
        "VenueID": 1,
        "category": "Tech",
        "date": "2025-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 27,
        "title": "Christmass carols",
        "description": "An amazing night of performances",
        "VenueID": 1,
        "category": "Tech",
        "date": "2025-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 3,
        "title": "AI for Africa Summit",
        "description": "Meet top minds working on responsible AI and digital policy for Africa.",
        "VenueID": 3,
        "category": "Data Science",
        "date": "2025-10-05",
        "time": "11:00 AM",
        "ticketsPrice": "5000.00",
        "totalTickets": 500,
        "soldTickets": 350,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 10,
        "title": "Deep Learning with TensorFlow Workshop",
        "description": "A full-day workshop on building AI models with TensorFlow and Keras.",
        "VenueID": 10,
        "category": "Data Science",
        "date": "2025-12-10",
        "time": "9:00 AM",
        "ticketsPrice": "4800.00",
        "totalTickets": 120,
        "soldTickets": 85,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 8,
        "title": "Frontend Masters Kenya",
        "description": "A frontend-focused event with sessions on React, Tailwind, and performance.",
        "VenueID": 8,
        "category": "Web Dev",
        "date": "2025-09-30",
        "time": "11:00 AM",
        "ticketsPrice": "1800.00",
        "totalTickets": 300,
        "soldTickets": 190,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 1,
        "title": "Google I/O Extended Nairobi",
        "description": "Explore the latest from Google technologies with the Nairobi dev community.",
        "VenueID": 1,
        "category": "Tech",
        "date": "2025-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 5,
        "title": "Google Cloud Day Nairobi",
        "description": "Hands-on training and talks on cloud-native development with GCP.",
        "VenueID": 5,
        "category": "Tech",
        "date": "2025-07-20",
        "time": "1:00 PM",
        "ticketsPrice": "2500.00",
        "totalTickets": 350,
        "soldTickets": 220,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 13,
        "title": "Lets meet Java User Group",
        "description": "Explore the latest from Google technologies with the Nairobi dev community.",
        "VenueID": 10,
        "category": "Tech",
        "date": "2025-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 15,
        "title": "Lets meet Java User Group",
        "description": "Explore the latest from Google technologies with the Nairobi dev community.",
        "VenueID": 6,
        "category": "Tech",
        "date": "2025-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 16,
        "title": "Google I/O Extended Nairobi",
        "description": "Explore the latest from Google technologies with the Nairobi dev community.",
        "VenueID": 1,
        "category": "Tech",
        "date": "2025-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 17,
        "title": "Google I/O Extended Nairobi",
        "description": "Explore the latest from Google technologies with the Nairobi dev community.",
        "VenueID": 1,
        "category": "Tech",
        "date": "2025-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 19,
        "title": "Lets meet Java User Group",
        "description": "Explore the latest from Google technologies with the Nairobi dev community.",
        "VenueID": 10,
        "category": "Tech",
        "date": "2025-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 20,
        "title": "AI for Africa Summit",
        "description": "Meet top minds working on responsible AI and digital policy for Africa.",
        "VenueID": 5,
        "category": "Data Science",
        "date": "2025-10-05",
        "time": "11:00 AM",
        "ticketsPrice": "5000.00",
        "totalTickets": 500,
        "soldTickets": 350,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-10-05",
        "updatedAt": "2025-10-05"
    },
    {
        "EventID": 21,
        "title": "AI for Africa Summit",
        "description": "Meet top minds working on responsible AI and digital policy for Africa.",
        "VenueID": 5,
        "category": "Data Science",
        "date": "2025-10-05",
        "time": "11:00 AM",
        "ticketsPrice": "5000.00",
        "totalTickets": 500,
        "soldTickets": 350,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-10-05",
        "updatedAt": "2025-10-05"
    },
    {
        "EventID": 14,
        "title": "Lets meet Java User Group",
        "description": "Explore the latest from Google technologies with the Nairobi dev community.",
        "VenueID": 6,
        "category": "Tech",
        "date": "2024-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 18,
        "title": "Google I/O Extended Nairobi",
        "description": "Explore the latest from Google technologies with the Nairobi dev community.",
        "VenueID": 10,
        "category": "Tech",
        "date": "2024-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 28,
        "title": "Updated Concert Night",
        "description": "Now with more artists!",
        "VenueID": 1,
        "category": "Tech",
        "date": "2024-08-10",
        "time": "10:00 AM",
        "ticketsPrice": "2000.00",
        "totalTickets": 300,
        "soldTickets": 180,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    },
    {
        "EventID": 2,
        "title": "Microsoft Build Africa",
        "description": "Join experts as we explore Microsoft's future in cloud and AI development.",
        "VenueID": 2,
        "category": "Web Dev",
        "date": "2024-08-10",
        "time": "9:00 AM",
        "ticketsPrice": "3500.00",
        "totalTickets": 400,
        "soldTickets": 240,
        "image_url": "https://res.cloudinary.com/dzysb2qhd/image/upload/v1753007171/samples/man-on-a-street.jpg",
        "createdAt": "2025-07-07",
        "updatedAt": "2025-07-07"
    }
]
