
export const users = [
    {
        "UserID": 2,
        "firstName": "Brooke",
        "lastName": "Delacruz",
        "email": "brooke.delacruz@example.com",
        "phoneNumber": "+1-612-149-2512",
        "address": "979 Christopher Field, New Danielleside, AZ 84167",
        "password": "$2b$10$aQMdInIucAWNBIYJN6P1becqcUbFsAR9RIr6svmpK5L9kL9L8S7SO",
        "role": "user",
        "isVerified": false,
        "verificationCode": "392960",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 3,
        "firstName": "Monica",
        "lastName": "Green",
        "email": "monica.green@example.com",
        "phoneNumber": "+1-719-907-2194",
        "address": "269 Michael Avenue Suite 831, Torreston, DE 33302",
        "password": "$2b$10$ztTUxJTuhvy1eQ70MhQuh.R53gPgg4m2RtXZrhRUxaSY9Jf6vfQrm",
        "role": "host",
        "isVerified": false,
        "verificationCode": "711374",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 4,
        "firstName": "Nicholas",
        "lastName": "Yates",
        "email": "nicholas.yates@example.com",
        "phoneNumber": "+1-486-480-5774",
        "address": "63233 Fowler Parkway Apt. 723, Williamsview, AR 24589",
        "password": "$2b$10$WAD3C2AL/tfR7x16CAv8KusuNjI6XOxOTTLX//gqAIrH7psz3wdBm",
        "role": "user",
        "isVerified": false,
        "verificationCode": "965861",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 5,
        "firstName": "Rebecca",
        "lastName": "Hall",
        "email": "rebecca.hall@example.com",
        "phoneNumber": "+1-774-236-2817",
        "address": "3785 Huber Estate Apt. 979, Lake Kimberly, SD 08085",
        "password": "$2b$10$hL2bUkQGoC8mxR3Ul66W/OCV1AytN9ARuVf2a7gSKdwG2zaQQWQdG",
        "role": "user",
        "isVerified": false,
        "verificationCode": "341741",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 6,
        "firstName": "Megan",
        "lastName": "Wright",
        "email": "megan.wright@example.com",
        "phoneNumber": "+1-503-125-1470",
        "address": "049 Albert Fields, Lake Jacob, WI 53777",
        "password": "$2b$10$t8JLSQzZyDiIGcoe/xNSMePd6Mm9sTbD92Zx7OyQdV4mL3mGNcWnu",
        "role": "admin",
        "isVerified": false,
        "verificationCode": "458877",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 7,
        "firstName": "Elizabeth",
        "lastName": "Franklin",
        "email": "elizabeth.franklin@example.com",
        "phoneNumber": "+1-910-421-3273",
        "address": "3230 Cabrera Mews, Lake Bruceside, SC 23931",
        "password": "$2b$10$rsrXTBMOFEeF/m1b32Wb5u2WZrEgqkWnpGJcTV6DMarJ2QQ5lp9IO",
        "role": "host",
        "isVerified": true,
        "verificationCode": "460364",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 8,
        "firstName": "Pamela",
        "lastName": "Harper",
        "email": "pamela.harper@example.com",
        "phoneNumber": "+1-675-521-9391",
        "address": "2638 Brown Throughway, South Melinda, CO 97710",
        "password": "$2b$10$ob.VKPVqad8zWmiB3.LSIe2aCTXLtZhDaj7dHbYo0AvTtVwxJ1Dz.",
        "role": "user",
        "isVerified": true,
        "verificationCode": "258366",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 9,
        "firstName": "John",
        "lastName": "Carter",
        "email": "john.carter@example.com",
        "phoneNumber": "+1-188-898-7991",
        "address": "27901 Gina Track Apt. 816, New Johnmouth, KS 35911",
        "password": "$2b$10$b.hygrO.zvLLNFvQSq1/kuv.nor8FuBgMhVf.DNAEjeuJJQB376Hi",
        "role": "host",
        "isVerified": false,
        "verificationCode": "780440",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 10,
        "firstName": "Ashley",
        "lastName": "Jensen",
        "email": "ashley.jensen@example.com",
        "phoneNumber": "+1-444-824-1382",
        "address": "623 Caitlin Crossing Apt. 112, Turnerberg, TN 05787",
        "password": "$2b$10$Xht6gsXYSDUrOUluIHK4Z.K6n4VBynbtYNmP6jZjNVkn8oKMPRkUa",
        "role": "user",
        "isVerified": false,
        "verificationCode": "995573",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 11,
        "firstName": "David",
        "lastName": "Karanja",
        "email": "david123@example.com",
        "phoneNumber": "0796166200",
        "address": "Adison route",
        "password": "$2b$10$HdORJTlehYV8x5Ts1zIw6OeFA01u6D.Mn2PbtjlA7jebcXOqX9Q5S",
        "role": "user",
        "isVerified": false,
        "verificationCode": "801002",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 1,
        "firstName": "Jean",
        "lastName": "Smith",
        "email": "jean.smith123@example.com",
        "phoneNumber": "+1-781-445-5336",
        "address": "Unit 1520 Box 9259, DPO AA 89285",
        "password": "$2b$10$6S6H7rpqVoPfQUyIT5xDr.ZWRyq8wTgHh9Zh/uglZWhWGUdIY6l6a",
        "role": "admin",
        "isVerified": false,
        "verificationCode": "245274",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 25,
        "firstName": "Test",
        "lastName": "User",
        "email": "testuser1752588074715@example.com",
        "phoneNumber": "1234567890",
        "address": "Test Address",
        "password": "$2b$10$uHc5vrdzTilOzNi3hgLuP.JLK8lvlxNR4Ju.ZbgOn9dnYh1DlhK2a",
        "role": "user",
        "isVerified": false,
        "verificationCode": "984628",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 37,
        "firstName": "Test",
        "lastName": "User",
        "email": "testuser1752590499030@example.com",
        "phoneNumber": "1234567890",
        "address": "Test Address",
        "password": "$2b$10$0.L8A7KTctAm6QvmQLZq0uE9PTs77hC2XIUpVe11DgeCwaVNbGzce",
        "role": "user",
        "isVerified": false,
        "verificationCode": "119304",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 38,
        "firstName": "David",
        "lastName": "Karanja",
        "email": "asiagokevin9@gmail.com",
        "phoneNumber": "0796166200",
        "address": "Adison route",
        "password": "$2b$10$qIkNjla5jhIsUIyI.IsbLOveXkVLh6Ck82/288lo5Nhtamby8JJKK",
        "role": "user",
        "isVerified": false,
        "verificationCode": "522865",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    },
    {
        "UserID": 47,
        "firstName": "Test",
        "lastName": "User",
        "email": "user791627@example.com",
        "phoneNumber": "123456789",
        "address": "123 Street",
        "password": "$2b$10$iRu8AReUmXPQI8fApKtds.bOdHtXDNe.fEsCwDum7JC4t.jtu4NLu",
        "role": "user",
        "isVerified": false,
        "verificationCode": "609486",
        "image_url": null,
        "createdAt": null,
        "updatedAt": null
    }
]


